<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="7" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="29" started-at="2016-04-13T01:48:55Z" finished-at="2016-04-13T01:48:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="29" started-at="2016-04-13T01:48:55Z" finished-at="2016-04-13T01:48:55Z">
      <class name="com.testng.AssertJUnitTest">
        <test-method status="PASS" signature="testAssertEquals0()[pri:0, instance:com.testng.AssertJUnitTest@1e0f4f]" name="testAssertEquals0" duration-ms="11" started-at="2016-04-13T09:48:55Z" finished-at="2016-04-13T09:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssertEquals0 -->
        <test-method status="PASS" signature="testAssertEquals1()[pri:0, instance:com.testng.AssertJUnitTest@1e0f4f]" name="testAssertEquals1" duration-ms="1" started-at="2016-04-13T09:48:55Z" finished-at="2016-04-13T09:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssertEquals1 -->
        <test-method status="PASS" signature="testAssertFalse()[pri:0, instance:com.testng.AssertJUnitTest@1e0f4f]" name="testAssertFalse" duration-ms="1" started-at="2016-04-13T09:48:55Z" finished-at="2016-04-13T09:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssertFalse -->
        <test-method status="PASS" signature="testAssertNotNull()[pri:0, instance:com.testng.AssertJUnitTest@1e0f4f]" name="testAssertNotNull" duration-ms="1" started-at="2016-04-13T09:48:55Z" finished-at="2016-04-13T09:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssertNotNull -->
        <test-method status="PASS" signature="testAssertNotSame()[pri:0, instance:com.testng.AssertJUnitTest@1e0f4f]" name="testAssertNotSame" duration-ms="0" started-at="2016-04-13T09:48:55Z" finished-at="2016-04-13T09:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssertNotSame -->
        <test-method status="PASS" signature="testAssertTrue()[pri:0, instance:com.testng.AssertJUnitTest@1e0f4f]" name="testAssertTrue" duration-ms="0" started-at="2016-04-13T09:48:55Z" finished-at="2016-04-13T09:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssertTrue -->
        <test-method status="FAIL" signature="testFail()[pri:0, instance:com.testng.AssertJUnitTest@1e0f4f]" name="testFail" duration-ms="0" started-at="2016-04-13T09:48:55Z" finished-at="2016-04-13T09:48:55Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.fail(AssertJUnit.java:66)
	at com.testng.AssertJUnitTest.testFail(AssertJUnitTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFail -->
      </class> <!-- com.testng.AssertJUnitTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
